pipeline {
    agent any
       environment {
     def dirpath=sh(script: 'pwd')
       }
    stages{
        stage('package'){
            steps {
                sh  'mvn clean package --file configServer/pom.xml'
                sh 'echo iiiiiiiiiiiii:$PWD'
            }
        }
        stage('run'){
            agent{
                dockerfile {
                    customWorkspace '/configServer'
        		    filename 'Dockerfile' // optional because file name is standars
                    dir ${dirpath}'/configServer' //if dockerfile is not in root
        		    additionalBuildArgs  '--build-arg version=1.0'
        		    args '-t my-config-server'
                }
            }
            steps{
                sh 'echo End of running configServer'

            }

        }
    }
}
